name: CI

on:
  schedule:
  - cron: 0 0,8,16 * * *
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        i: [1, 2, 3]
        include:
          - i: 1
            symbol: "647"
            email: "cbosa-647@googlegroups.com"
            mode: "uzasadnione"
          - i: 2
            symbol: "648*"
            email: "cbosa-648@googlegroups.com"
            mode: "uzasadnione"
          - i: 3
            symbol: "647"
            email: "cbosa-647@googlegroups.com"
            mode: 'wszystkie'
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          submodules: true
      - name: Make dir for artifact
        run: mkdir -p artifact
      - name: Execute PHP
        run: ./update.sh
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_USER: "AKIATTWUTKSTQ2RLDQGQ"
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          SMTP_FROM: "cbosa-648@jawnosc.tk"
          SMTP_TO: "${{matrix.email}}"
          SYMBOL: "${{matrix.symbol}}"
          MODE: "${{matrix.mode}}"
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull origin master
          git commit -m "Update by GitHub Action for ${{matrix.symbol}} & ${{matrix.mode}}" *.json || echo "Nothing to update"
      - uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: artifact
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Show Proxy logs
        run: make logs
        if: failure()
